In [14]:
import numpy as np
a = np.zeros((2,3))

In [15]:
a

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [17]:
a[1,]=np.arange(3)

In [18]:
a

array([[ 0.,  0.,  0.],
       [ 0.,  1.,  2.]])

In [19]:
a


array([[ 0.,  0.,  0.],
       [ 0.,  1.,  2.]])

In [33]:
a = np.array([1,2,3,4,5,6])
b = np.array([4,5,6])

In [36]:
c = a.reshape(2,3)

In [37]:
c

array([[1, 2, 3],
       [4, 5, 6]])

In [38]:
b*c

array([[ 4, 10, 18],
       [16, 25, 36]])

In [40]:
d =c*b

In [44]:
d


array([[ 4, 10, 18],
       [16, 25, 36]])

In [46]:
np.sum(d, axis=1)

array([32, 77])

In [48]:
np.shape(np.linspace(-8,8,64))

(64,)

In [49]:
np.zeros(3)


array([ 0.,  0.,  0.])

In [50]:
np.len(a)

AttributeError: 'module' object has no attribute 'len'

In [51]:
np.size(a)

6

In [52]:
len(a)

6

In [35]:
c

array([[1, 2],
       [3, 4],
       [5, 6]])

In [21]:
a**2

array([1, 4, 9])

In [22]:
abs(a)**2

array([1, 4, 9])

In [7]:
c= a*b


In [8]:
c


array([ 4, 10, 18])

In [9]:
a

array([1, 2, 3])

In [10]:
h = np.tile(a,(3,1))

In [11]:
h

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [12]:
h*a.T

array([[1, 4, 9],
       [1, 4, 9],
       [1, 4, 9]])

In [23]:
g = np.zeros(3)
g

array([ 0.,  0.,  0.])

In [24]:
g[1]=3

In [25]:
g

array([ 0.,  3.,  0.])

In [30]:
def f(u, t):
    return 1j*w*u

import odespy, numpy

w = 2*numpy.pi
solver = odespy.RK4(f, complex_valued=True)
A= np.array([1,0,0])
solver.set_initial_condition(A)
u, t = solver.solve(numpy.linspace(0, 6, 101))

In [31]:
np.shape(u)

(101, 3)

In [32]:
np.zeros((2,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [28]:
numpy.shape(u)


(101,)